#!/bin/sh

if [ -n "$SWAYSOCK" ]; then
    LOCKER="swaylock -f -c 000000"
    LOGOUT="swaymsg exit"
else
    LOCKER="i3lock -c 000000"
    LOGOUT="i3-msg exit"
fi

entries="Lock,Logout,Suspend,Reboot,Shutdown"

selected=$(echo $entries | rofi -m 0 -dmenu -sep ',' -p "power" -i | awk '{print tolower($1)}')

case $selected in
  lock)
    $LOCKER;;
  logout)
    $LOGOUT;;
  suspend)
    $LOCKER & exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
